; Disassembled by yanming.J
; SPDX-License-Identifier: MIT
; https://github.com/yanmingsohu/

; Exports for C
_pt_99ce20 dword $L_99ce20
  public _pt_99ce20
_pt_99ce34 dword $L_99ce34
  public _pt_99ce34
_pt_99ce38 dword $L_99ce38
  public _pt_99ce38
_pt_99ce3c dword $L_99ce3c
  public _pt_99ce3c
_pt_scr_h_width Dword $L_517438
  public _pt_scr_h_width
_pt_scr_h_height Dword $L_51743c
  public _pt_scr_h_height

; 这个方法 c 没法调用
;_truncate_d dword truncate_d
;public _truncate_d